import type { Metadata } from "next";
import { Chivo, Judson } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const chivo = Chivo({
  subsets: ["latin"],
  variable: "--font-chivo",
});
const judson = Judson({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-judson",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${judson.variable} ${chivo.variable}`}>
        <Providers attribute="class" defaultTheme="dark">
          {children}
        </Providers>
      </body>
    </html>
  );
}
